import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import "./globals.css";
import ContainerProvider from "@/components/Providers/container.provider";
import Navbar from "@/components/Navbar";
import Prism from "@/components/Prism";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Earl.Creatives",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistMono.className} antialiased`}>
        <ContainerProvider>
          <Navbar>{children}</Navbar>
        </ContainerProvider>
      </body>
    </html>
  );
}
